development:
  adapter: postgresql
  encoding: unicode
  database: topicstarter_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: topicstarter_test
  pool: 5
  username:
  password:
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
